# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
getLQ <- function(d) {
    .Call('_mhstability_getLQ', PACKAGE = 'mhstability', d)
}

#' @export
#' @import Rcpp
getR <- function(d) {
    .Call('_mhstability_getR', PACKAGE = 'mhstability', d)
}

rcpp_hello <- function() {
    .Call('_mhstability_rcpp_hello', PACKAGE = 'mhstability')
}

